# Generated by Django 3.1.7 on 2021-03-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of schema', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnInSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of column', max_length=200)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.schema')),
            ],
        ),
    ]
