# Generated by Django 3.1.7 on 2021-03-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_from_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_name_1',
            field=models.CharField(help_text='name of column', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_order_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_to_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_type_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ColumnInSchema',
        ),
    ]
