# Generated by Django 3.1.7 on 2021-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210315_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_from_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_from_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_name_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_name_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_order_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_order_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_to_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_to_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_type_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='column_type_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_name_1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
