# Generated by Django 3.1.7 on 2021-03-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.schema'),
        ),
    ]
